### ISSUE TITLE
Generating binary data causes an error

### ISSUE THREAD

**Issue by fcracker79** [teddziuba/django-sslserver#31]
Greetings,

I have noticed that if my view returns a binary document (a PDF document in my case), I receive the following error:

    [29/Mar/2015 20:10:13] "POST /wallet/pdf_backup_key/ HTTP/1.1" 200 0
    Traceback (most recent call last):
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 138, in run
        self.finish_response()
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 180, in finish_response
        self.write(data)
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 279, in write
        self._write(data)
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 453, in _write
        self.stdout.write(data)
      File "/usr/lib/python3.4/socket.py", line 391, in write
        return self._sock.send(b)
      File "/usr/lib/python3.4/ssl.py", line 679, in send
        v = self._sslobj.write(data)
    ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1636)

My code is the following:
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="backup_key.pdf"'
    p = canvas.Canvas(response)
    # Here I add some elements in my PDF document
    p.showPage()
    p.save()
    return response

What is noticeable is that in normal http mode it works perfectly.

I have discovered that the class `HttpResponse`, by default, creates a content which is `b''`, which does not seem to be allowed by ssl. It is not important if, later, I add further data (my pdf document).
I have temporarily solved the problem by specifying a content, such as `response = HttpResponse(content='hello', ...)`, but it is a silly solution.

**Comment by battlemidget** [comment]
My time is a bit limited these days so a PR would definitely help!

**Comment by kylemacfarlane** [comment]
I have the same error whenever I respond with a redirect (redirects obviously have no body) and it's pretty noisy.

There's two causes to this problem:

1) Django's default content for HttpResponse is `b''`. They chose this because it makes building the response and checking it's length much simpler.
2) ``wsgiref.handlers.BaseHandler.finish_response`` just blindly sends all items from the response iterator even if it's an empty value.

A solution is to change `finish_response` to something like the following:

    def finish_response(self):
        try:
            if not self.result_is_file() or not self.sendfile():
                for data in self.result:
                    if data:
                        self.write(data)
                self.finish_content()
        finally:
            self.close()

I thought this would work without monkey patching if I added it as a method to ``sslserver.management.commands.runsslserver.WSGIRequestHandler`` but it never gets called. It seems like there's some weird inheritance and/or the default request handler still gets used in some places.

Any ideas? It's an easy fix if you know where to put the code.

**Comment by edwardotis** [comment]
So, while digging through this bug, I tested the django-sslserver selfsigned cert and key with gunicorn 19.4.3 and django 1.8

The results are no SSLEOFError errors for either case:
-- django redirects
-- downloads

cmd line:
gunicorn myapp.wsgi  --keyfile  ./<your-path-to>/development.key --certfile ./<your-path-to>/development.crt

Also, by launching gunicorn from within pycharm ide, I get full debugging of breakpoints. So, all my use cases for ssl based development are satisfied with this workaround.

**Comment by sethlivingston** [comment]
I ran into this error while testing the Django syndication feeds locally. I just switched off local SSL to test them, and they work fine in production.

**Comment by ssokolow** [comment]
I ran into this error and worked around it by copying `wsgiref` into my virtualenv and then applying the change @kylemacfarlane posted.

**Comment by sharpTrick** [comment]
I put the following @kylemacfarlane code in the \__init__.py file that shares a directory with settings.py.

```
from wsgiref.handlers import BaseHandler


def finish_response(self):
    try:
        if not self.result_is_file() or not self.sendfile():
            for data in self.result:
                if data:
                    self.write(data)
            self.finish_content()
    finally:
        self.close()


BaseHandler.finish_response = finish_response
```

It appears to have done the trick for me in my limited testing. I confirmed that it was called with every page refresh by adding a print statement.
