### ISSUE TITLE
ssl.SSLEOFError error on 302 login redirect response

### ISSUE THREAD

**Issue by edwardotis** [teddziuba/django-sslserver#41]
Hello,

When using Django AllAuth, the server issues a redirect after login, signup, logoff etc.
This causes an SSLEOFError error when using django-sslserver.  The redirect succeeds, but the following is written to the log. 

[21/Dec/2015 09:14:47] "GET /accounts/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 453, in _write
    self.stdout.write(data)
  File "/usr/lib/python3.4/socket.py", line 394, in write
    return self._sock.send(b)
  File "/usr/lib/python3.4/ssl.py", line 702, in send
    v = self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1638)

When running the same flow on heroku, the redirects to not cause any ssl errors.

https://pypi.python.org/pypi/django-allauth
allauth.account.adapter.DefaultAccountAdapter#get_login_redirect_url

python 3.4.3
Django==1.8.6
django-sslserver==0.18
django-allauth==0.24.1

**Comment by edwardotis** [comment]
This might be a solution.
http://docs.gunicorn.org/en/19.4.3/settings.html#suppress-ragged-eofs

**Comment by edwardotis** [comment]
a. suppress-ragged-eofs defaults to True, and was already enabled in django-sslserver, so that has no impact.

b. I see my issue is a duplicate of:
https://github.com/teddziuba/django-sslserver/issues/31
