### ISSUE TITLE
Django <=1.7 versions are not supported any more. Update dependency in setup.py

### ISSUE THREAD

**Issue by myrs** [teddziuba/django-sslserver#42]
Hello!

It seams like actual version of `django-sslserver` doesn't really support version of Django 1.7 and older, as `django.core.management.commands.BaseCommand.add_arguments` doesn't exist in this versions. Execution of `python manage.py runsslserver` results in

```
Unhandled exception in thread started by <function wrapper at 0x7f4cff6ae9b0>
Traceback (most recent call last):
  File "path_to_virtualenv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 222, in wrapper
    fn(*args, **kwargs)
  File "path_to_virtualenv/local/lib/python2.7/site-packages/sslserver/management/commands/runsslserver.py", line 109, in inner_run
    self.check_certs(key_file, cert_file)
  File "path_to_virtualenv/local/lib/python2.7/site-packages/sslserver/management/commands/runsslserver.py", line 97, in check_certs
    if not os.path.exists(key_file):
  File "path_to_virtualenv/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

Should dependency in `setup.py` be updated to `Django >= 1.8` (`Django >= 1.4` now)?

P.S. Seem like the last version of django-sslserver supporting Django 1.7 is 0.15

**Comment by battlemidget** [comment]
Yea makes sense to update the dependency version, PR very welcomed otherwise I'll try to get to this next week

**Comment by myrs** [comment]
Great, created PR: #43
